# This is a sample plugin.yml
# For more information refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.smmattic.DataDemo.DataDemo
name: ${project.name}
version: ${project.version}
author: SampleAuthor
description: ${project.description}
commands:
  blessing:
    description: all commands begin with bless
    usage: blessing /<command> arguments
    permission: blessing.*
permissions:
  blessing.*:
    description: gives all permissions of the SamplePlugin
    default: true
    children:
      blessing.message:
        description: gives permission to set the greeting message 
      blessing.bless:
        description: grants a 'blessing' 
      blessing.none:
        description: will not grant a blessing

        